import {Dimensions, StyleSheet} from 'react-native';
import color from '../../constant/color';
import _const from '../../constant/const';
const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: color.secondary50,
  },
  content: {
    marginHorizontal: 18,
  },
  feedbackheaderstyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 0,
  },
  backButtonContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: color.secondary200,
  },
  title: {
    fontFamily: _const.blissBold,
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 36,
    marginTop: 28,
    color: color.neutral900,
  },
  subtitle: {
    fontFamily: _const.blissRegular,
    fontSize: 18,
    fontWeight: '400',
    marginTop: 8,
    color: color.neutral900,
    lineHeight: 27,
  },
  dropdownContainer: {
    borderWidth: 1,
    borderColor: color.neutral300,
    borderRadius: 8,
    marginTop: 36,
  },
  selectContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: color.white00,
    borderRadius: 8,
  },
  selectedTitle: {
    width: '88%',
    fontFamily: _const.blissRegular,
    fontSize: 18,
    fontWeight: '400',
    lineHeight: 27,
    color: color.neutral700,
  },
  downArrowContainer: {
    marginLeft: 10,
    width: 26,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalWrapper: {
    backgroundColor: 'white',
    width: '100%',
    height: 258,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  modalContent: {
    marginTop: 29,
    marginHorizontal: 18,
  },
  modalHeaderContainer: {
    flexDirection: 'row',
    textAlign: 'center',
    paddingTop: 21,
  },
  feedbackTitle: {
    fontSize: 20,
    fontFamily: _const.blissBold,
    fontWeight: '700',
    lineHeight: 26,
    color: color.primary700,
    flexGrow: 1,
  },
  cancelButtonContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    backgroundColor: color.neutral100,
    borderRadius: 15,
    position: 'absolute',
    top: -20,
    right: 0,
  },
  rateContainer: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: color.neutral200,
    paddingTop: 12,
    paddingBottom: 16,
    marginTop: 24,
  },
  reportContainer: {
    flexDirection: 'row',
    paddingTop: 12,
    paddingBottom: 16,
    marginTop: 4,
  },
  listInfo: {
    flexGrow: 1,
    fontFamily: _const.blissRegular,
    fontSize: 18,
    fontWeight: '400',
    lineHeight: 27,
    color: color.neutral900,
  },
  ratingContainer: {
    marginTop: 34,
  },
  ratingText: {
    fontFamily: _const.blissMedium,
    fontWeight: '500',
    fontSize: 18,
    lineHeight: 27,
    color: color.neutral900,
  },
  starImageContainer: {
    marginTop: 12,
    gap: 16,
    flexDirection: 'row',
  },
  starContent: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    backgroundColor: color.white00,
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: color.white00,
  },
  selectedStarContent: {
    borderWidth: 1.5,
    borderColor: color.primary500,
  },
  feedbackContainer: {
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 27,
    fontFamily: _const.blissMedium,
    marginTop: 32,
  },
  textAreaContainer: {
    marginTop: 12,
  },
  textInput: {
    borderRadius: 6,
    borderWidth: 0.5,
    backgroundColor: color.white00,
    borderColor: color.neutral300,
    height: 175,
    paddingHorizontal: 12,
    paddingVertical: 16,
    fontSize: 16,
    fontFamily: _const.blissLight,
    fontWeight: '200',
    lineHeight: 24,
  },
  textInputFocus: {
    borderWidth: 1,
    borderColor: color.primary500,
  },
  bottomButtonContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    alignSelf: 'center',
    paddingVertical: 16,
    backgroundColor: color.secondary100,
    paddingHorizontal: 18,
  },
  scrollViewContainerStyle: {
    paddingBottom: 100,
  },
  errortext: {
    fontFamily: _const.blissRegular,
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    color: color.red,
    marginLeft: 4,
  },
  row: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'flex-start',
    marginTop: 12,
    alignSelf: 'stretch',
  },
  screeenLoaderContainer: {
    height: Dimensions.get('screen').height * 0.75,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lastReatedContainer: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    marginTop: 12,
  },
  lastReatedText: {
    fontFamily: _const.blissRegular,
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 20.8,
    color: color.neutral500,
    marginLeft: 4,
  },
  starContentWithoutBG: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
});

export default styles;
